apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-depl
  name: nginx-depl
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-depl
  type: NodePort
status:
  loadBalancer: {}
