resources:
  - api
#  - cache
  - db

labels:
  - pairs:
      company: Vitali

patches:
  - target:
      kind: Deployment
      name: nginx-depl
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
